version: '3.8'

services:
  frontend:
    build:
      context: ./FrontendElog
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./BackEndElog
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
